"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const Confronto_1 = require("./Inimigos/Confronto");
const ReiOssos_1 = require("./Inimigos/ReiOssos");
const Bardo_1 = require("./Personagens/Bardo");
// let personagem = criaPersonagem();
// clear();
// arteInfoJogo();
// stop();
// inicio(personagem);
(0, Confronto_1.iniciarConfronto)(new Bardo_1.Bardo('Ju'), new ReiOssos_1.ReiOssos());
